# Generated by Django 5.2.3 on 2025-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="discarded_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batch",
            name="solved_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batch",
            name="total_generated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="batch",
            name="valid_count",
            field=models.IntegerField(default=0),
        ),
    ]
