# Generated by Django 5.2.3 on 2025-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("math_agent", "0002_batch_discarded_count_batch_solved_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="discarded_count",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="solved_count",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="total_generated",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="valid_count",
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="similar_problems",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
